import { Client, Theme } from "@/lib/types";

export const exampleClient: Client = {
  id: 1,
  name: "Preview Earthly Elegance",
  slug: "preview-earthly-elegance",
  address: "Bali",
  address_url: "https://maps.app.goo.gl/ifA1t8ig388u2quj8",
  cover:
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-zwfBTMwqXtTdcjeUeOxfP85ODvem55.jpeg",
  address_full: "Kab. Badung, Bali, Indonesia",
  theme_id: 1,
  date: "2024-10-08",
  start_time: "14:00",
  end_time: "Selesai",
  gallery: [
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-f4yfgylwOY1bIOzrpjSqVJeLpYAmho.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-dh4uWuK4Mnbc0TA9PjQpTAiISzuHaw.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-ZURRwRYKJ2MhMzNsK9SQV8g2xAwoSX.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-0FiwD2vFaimsPLh6kAkv0wvGXZRCyM.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-ozN1tL38LVff2NC8FJPk6z4hBaFxLu.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-Uix8z4oHx4grJjmBrzByYh36raNTXj.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-CbfrV0GR8B8HdBY8HnSbp4YojkPewg.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-QwGGdz7RXALTYxJPK7nTkmjdOQPpC5.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-h3iF4Vo1Uhf3kFCD7ZFdIbkX1OeogB.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-zwfBTMwqXtTdcjeUeOxfP85ODvem55.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-PWGt78nPOqraYs58GrE7Se04UrcEoA.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-Q5hkdqpX9oaWnBElNOvHIjir4rarvL.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-dSJY0L9F45CrIK6nxPs5VJfbvA2TUH.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-H11aMRrlt2evPUu9ecXJ09g4xNrO7I.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-0ZW6Z7MPGgJz2ME9h6BFbRov1mejK3.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-gnlhv7Ic3JsowN85Qwcw2VJpcHYNxM.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-LNh3RXTtqzeYG4VYB93QokQ3RnHE9V.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-bOLScPY1Zgn6BClbcNuYsYhj9YyhOP.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-tfooCiloRNeULAVQamvLehHw5zFqsk.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-9G60ADriYbURDNMNqAYTa6TqVGnctA.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-FcQgGb1qbpi4xUb8wmSepn4dYsOAmO.jpeg",
    "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/gallery-preview-earthly-elegance-LUq8kkt0FJAar86RQvLHx9OaZYAzj5.jpeg",
  ],
  status: "paid",
  created_at: "2024-10-05T10:34:37.428Z",
  updated_at: "2024-10-05T10:34:37.428Z",
  participants: [
    {
      id: 2,
      client_id: 1,
      name: "Ni Made Eka Putri",
      nickname: "Eka",
      address: "Jimbaran, Kec. Kuta Selatan, Kab. Badung, Bali, Indonesia",
      child: "kedua",
      parents_male: "I Made Suastika",
      parents_female: "Ni Putu Darmi",
      image:
        "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/participant-ni-made-eka-putri-8RXasN6tex1eWyjCggnWbP3G5g6qKq.jpeg",
      gender: "female",
      role: "bride",
      created_at: "2024-10-05T10:34:38.304Z",
      updated_at: "2024-10-05T10:34:38.304Z",
    },
    {
      id: 1,
      client_id: 1,
      name: "I Gede Wahyu Darma Putra",
      nickname: "Wahyu",
      address: "Kerobokan, Kec. Kuta Utara, Kab. Badung, Bali, Indonesia",
      child: "pertama",
      parents_male: "I Wayan Darma Putra",
      parents_female: "Ni Made Santika",
      image:
        "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/participant-i-gede-wahyu-darma-putra-n47azWdCKCYOLQ3nGd4vDVsH5hYRw7.jpeg",
      gender: "male",
      role: "groom",
      created_at: "2024-10-05T10:34:37.649Z",
      updated_at: "2024-10-05T10:34:37.649Z",
    },
  ],
  theme: {
    id: 1,
    name: "Earthly Elegance",
    thumbnail:
      "https://0i9ria69mw7glx7c.public.blob.vercel-storage.com/meundang/thumbnail-earthly-elegance-oLQEjD7hWGzreEDfZRlgsiDfGc3TdF.png",
    price: 150000,
    created_at: "2024-10-05T10:28:35.582Z",
    updated_at: "2024-10-05T10:28:35.582Z",
  },
};
